version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messagedatabase
    ports:
      - "5430:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 15

  api:
    image: messageservice
    build:
      context: .
      dockerfile: MessageService/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
    volumes:
      - ./logs:/app/logs

  webclient:
    image: webclient
    build:
      context: .
      dockerfile: WebClient/Dockerfile
    depends_on:
      - api
    ports:
      - 80:8080


networks:
  mynetwork:
    driver: bridge